### PR TITLE
Initial iOS support.

### PR DESCRIPTION
**Pull request by diegoreymendez**
### Description

This PR adds initial support for iOS.  It allows running the project in iOS and loading a very simple (solid blue) view - as a placeholder for Aztec.

### Details:

There are several changes included in this PR due to several issues I had to deal with in iOS:

- Added two identical .gitignore files for Xcode / Swift / ObjC ([one](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-d7c35f6840db1950f2da9713671b70ddR1) for the example project, and [one](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-88fb5bc44eff8c82891374d0ae90f56aR1) for the root project).  They're both a copy of [GitHub's Swift `.gitignore` file](https://github.com/github/gitignore/blob/master/Swift.gitignore).  The reason I kept them in the Xcode project folder is to make it easier to update them by just overwriting the files.  The added bonus is that Android devs don't need to care about iOS's files.  The downside is the `.gitignore` file is duplicated.  Feel free to criticize!
- The root `package.json` [no longer tries to clean the example App](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L8).  The rationale is that the library shouldn't care about the example App's caches.
- Added [a clean and clean:install procedure](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-012ac553d93d987b8d34ad013052bc96R11) to the example app's `package.json` file.
- Added [some iOS cleaning procedures](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-012ac553d93d987b8d34ad013052bc96R12) which shouln't run if Xcode isn't installed.
- Added a `yarn clean cache --force` call to both [the root](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R8) and [the example app's](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-012ac553d93d987b8d34ad013052bc96R11) clean procedures.
- Updated [the `react` and `react-native` dependencies](https://github.com/wordpress-mobile/react-native-aztec/pull/12/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12) to be compatible with Xcode 9.3.
- Updated `yarn.lock`, although I'm not sure if that's necessary - let me know if it's appropriate to roll that back.

### Additional Info

<details><summary>Expand to see .babelrc error log</summary>

```
error: bundling failed: Error: Unable to resolve module `./node_modules` from `/Users/diego/Developer/react-native-aztec/example/App.js`: The module `./node_modules` could not be found from `/Users/diego/Developer/react-native-aztec/example/App.js`. Indeed, none of these files exist:

  * `/Users/diego/Developer/react-native-aztec/example/node_modules(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/diego/Developer/react-native-aztec/example/node_modules/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/diego/Developer/react-native-aztec/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```
</details>

### Important

Please note that I haven't tested how my changes impact Android because I don't have the environment set-up yet (work in progress).  So test carefully and let me know if there's any problem.

### Testing

- Do `yarn:clean install` in the root directory.  Make sure all is fine.
- Do `yarn:clean install` in the `example` directory.  Make sure all is fine and the new iOS cleaning procedures don't show errors.  Make sure `example/node_modules/react-native-aztec` exists.
- Run the Android example project and make sure there are no errors.
- Run the iOS example project and make sure a blue view (placeholder view) is displayed.

screen shot 2018-04-18 at 13 37 02

### CODE REVIEW

**Comment by diegoreymendez** [comment]
I'll be processing all feedback as soon as @hypest reviews the PR but wanted to clarify this:

> I'm not sure what the error log added in the Additional info means. Is this something that you found while writing this and is fixed, or is something that appears but doesn't seem to be a blocker for you?

That wasn't very clear, sorry... it's the error I was getting that forced me to remove the `.babelrc` alias and replace it with the change in `package.json`.  Once I did that, the error went away.

**Comment by maxme** [comment]
> Updated the react and react-native dependencies to be compatible with Xcode 9.3.

**Comment by maxme** [comment]
> The .babelrc alias we had was causing an error in iOS. I replaced it with a change in package.json so that the library will be installed normally. This has the added advantage of letting us test the library as it would be used by any other App (such as WP)

I don't know what was your issues, but it's not incompatible with iOS (we use this in the recyclerlist library and it works well). Having the babel module resolver also gives us the advantage of using the library like it would be in any other app (and the code can be copy/pasted from the example to any other app).

**Comment by diegoreymendez** [comment]
> I don't know what was your issues, but it's not incompatible with iOS (we use this in the recyclerlist library and it works well).

It's basically just the log reported in the "Additional Details" section.  Not sure how it was solved in recyclerlist, but I believe this is ultimately secondary to...

> Having the babel module resolver also gives us the advantage of using the library like it would be in any other app (and the code can be copy/pasted from the example to any other app).

I'm not sure I follow the reasoning here.

External Apps wouldn't use this library through a `.babelrc` alias, but rather through a `package.json` dependency thats fulfilled when doing `npm | yarn install`.

This will in turn install the library inside `nodes_module` (as my PR does), and then you can link to the library from it (this is what the example App does for iOS - it doesn't include any sources from the base directory directly).

The `.babelrc` alias was basically not installing any of the library inside `node_modules`.

**Comment by maxme** [comment]
> The .babelrc alias was basically not installing any of the library inside node_modules.

Yes, but it "simulates" the package being installed in `node_modules`, in an example configuration we don't want the library being installed in the `node_modules` because you have to run `yarn install` everytime you edit the library and there are other issues with using `file://..` (unfortunately I don't remember which issues, I had so many of them when I had to setup the example project...).

**Comment by diegoreymendez** [comment]
Rolled back changes by request of @maxme.

The thing that solved the original issues I was seeing is running: `yarn cache clean --force`

Mind-blown that this is not taken care of by `yarn cache clean --force`.

**Comment by diegoreymendez** [comment]
Removed the `yarn cache clean --force` command, and updated the GitHub issue description @maxme.

**Comment by diegoreymendez** [comment]
> Did you use react-native-git-upgrade to upgrade? Some changes might have to be done on the native side (Android and iOS) in order to be compatible with the latest RN version.

Nopes.  The ios project had been removed from this repo so I had to create it from scratch and move it over from another project.

It was kinda painful but it seems everything's working more or less fine, right now.

**Comment by diegoreymendez** [comment]
@mzorz - Thanks for the review:

> I think we can probably merge both into one in the root folder alone, making expressions that contain all the files that need be ignored. FWIW we can do on a separate PR though.

[Unified](https://github.com/wordpress-mobile/react-native-aztec/pull/12/commits/964f62ee7776eaa1646ede4ac0d0fa935eaf4f75) the `.gitignore` files into the root one.

> I'm ok with this as long as we still add the clean command to the example app's package.json, as an enhancement. Which of course you already did :D, so 👍

Done!

Let me know if everything looks fine.

**Comment by hypest** [comment]
👋 @diegoreymendez, I did a review pass as requested and have nothing to add as feedback except for the fact that on my Xcode 8.2.1 (8C1002) setup I run into the "Actual Behavior" found on https://github.com/facebook/react-native/issues/18944 and the example app doesn't compile.

**Comment by diegoreymendez** [comment]
@hypest - Thanks!  At this point Xcode 9.3 is going to be a requirement (due to many many changes), so that's fine.

You may want to upgrade, though.  Let me know if you need assistance.

**Comment by mzorz** [comment]
Thank you again for your work @diegoreymendez and thank you @maxme @hypest for your reviews, there are many things in your comments that I didn't know about, so always learning here 👍 

:shipit:

**Comment by hypest** [comment]
Commenting here so it doesn't fall through the cracks, can you please update the README.md to include the Xcode 9.3+ requirement @diegoreymendez ? Thanks!

**Comment by daniloercoli** [comment]
Late to the party! 
Tried it on 9.2 and worked without issues. Just had a warning in console that highlighted this prj was written by a newer Xcode. 
`Referenced project RNTAztecView was written by a newer Xcode version (50)`

**Comment by diegoreymendez** [comment]
@daniloercoli - Yeah... the Xcode 9.3 compatibility issues will come up once we start including the real Aztec view, as it's Xcode 9.3+ only.

**Pull request merged**
